import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {flex: 1, justifyContent: 'center'},
  title: {flex: 1, alignItems: 'center', justifyContent: 'flex-end'},
  textTitle: {
    color: '#02193E',
    fontWeight: 'bold',
    fontSize: 35,
  },
  avoidingView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerSocialLogin: {alignItems: 'center', flex: 4},
  textContinue: {
    color: '#02193E',
    fontWeight: 'bold',
    fontSize: 20,
    marginBottom: 5,
  },
  loginText: {
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
    marginTop: 5,
    marginBottom: 10,
    alignSelf: 'flex-start',
    marginLeft: 20,
  },
  input: {
    width: '90%',
    height: 50,
    backgroundColor: '#333',
    borderRadius: 6,
    marginTop: 10,
    paddingHorizontal: 10,
    fontSize: 16,
    color: '#808e9b',
  },
  signupButton: {
    backgroundColor: 'olivedrab',
    paddingVertical: 12,
    borderRadius: 6,
    marginTop: 15,
    width: '85%',
  },
  signinButton: {
    backgroundColor: '#02193E',
    paddingVertical: 12,
    borderRadius: 6,
    marginTop: 15,
    width: '85%',
  },
  loginButtonText: {
    fontSize: 20,
    fontWeight: '500',
    color: '#fafafa',
    alignSelf: 'center',
  },
  loginWithBar: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 50,
  },
  iconFacebook: {marginLeft: 35},
  iconGoogle: {marginRight: 35},
  registerButton: {
    borderRadius: 6,
    marginTop: 10,
    marginBottom: 10,
    width: '70%',
  },
  registerButtonText: {
    fontSize: 20,
    fontWeight: '500',
    color: 'olivedrab',
    alignSelf: 'center',
  },
  linesLeft: {
    backgroundColor: '#02193E',
    height: 2,
    flex: 1,
    alignSelf: 'center',
    marginLeft: 25,
    marginRight: 5,
  },
  linesRight: {
    backgroundColor: '#02193E',
    height: 2,
    flex: 1,
    alignSelf: 'center',
    marginRight: 25,
    marginLeft: 5,
  },
  textBetweenLines: {
    alignSelf: 'center',
    paddingHorizontal: 5,
    fontSize: 20,
    color: '#02193E',
  },
});
